[tryspaceorg/tryspace-lab#54] build-cli updated to avoid docker calls;

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -87,4 +87,9 @@ jobs:
           cd cfg
           python3 tryspace-orchestrator.py
           cd ..
-          make cli
+          for dir in $(pwd)/comp/*/cli ; do
+            if [ -f "$dir/Makefile" ]; then
+              echo "Building CLI component in $dir"
+              make -C "$dir" build-cli || { echo "Failed building $dir"; exit 1; }
+            fi
+          done
