[#51] Strict build flags (#67)
* [tryspaceorg/tryspace-lab#51] Modifications after CompFlags.cmake improvements;

* [tryspaceorg/tryspace-lab#51] Separate flags for unit tests;

* [tryspaceorg/tryspace-lab#51] CLI updates for strict flags;

* [tryspaceorg/tryspace-lab#54] CLI CI;

* [tryspaceorg/tryspace-lab#54] build-cli updated to avoid docker calls;

* [tryspaceorg/tryspace-lab#51] Submodule updates after merges;

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -71,3 +71,25 @@ jobs:
         with:
           verbose: true
           recurse_submodules: true
+
+  build-cli:
+    runs-on: ubuntu-latest
+    container:
+        image: tryspaceorg/tryspace-lab:0.0.1
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+          fetch-depth: 1
+      - name: Build CLI
+        run: |
+          cd cfg
+          python3 tryspace-orchestrator.py
+          cd ..
+          for dir in $(pwd)/comp/*/cli ; do
+            if [ -f "$dir/Makefile" ]; then
+              echo "Building CLI component in $dir"
+              make -C "$dir" build-cli || { echo "Failed building $dir"; exit 1; }
+            fi
+          done
